<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RiderLayout.Core\RiderLayout.Core.csproj" />
    <ProjectReference Include="..\RiderLayout.Rider\RiderLayout.Rider.csproj" />
    <ProjectReference Include="..\RiderLayout.CSharp\RiderLayout.CSharp.csproj" />
  </ItemGroup>
</Project>
